---
language: ruby

services: docker

os: linux
dist: bionic

env:
  global:
    - DOCKER_IMAGE_ID="${DOCKER_USERNAME}/ubuntu"

before_install:
  - ./.travis/main.sh

before_script:
  - docker version

# First execute the test suite.
# After the test execution is done and didn't fail, build the images
# (if this step fails the whole Travis build is considered a failure).
script:
  - cd ubuntu/20.04
  - make test
  - make image

# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD` filled you need to either use `travis`' cli and then `travis set ..`
# or go to the travis page of your repository and then change the environment in the settings pannel.
deploy:
  # Deploy docker image to registry
  - provider: script
    script: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin && make push-image
    on:
      branch: master
